### ISSUE TITLE
Error running gulp (missing /dist directory)

### ISSUE THREAD

**Issue by vbabaria** [przeor/react-router-flux-starter-kit#12]
thanks for the demo... i get following error while running gulp command

also for some reason running "gulp" command didn't create directory "reactJS-flux-starter-kit/dist/" as per ReadMe file - am i missing something obvious? - thanks

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at ConnectApp.server (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/node_modules/gulp-connect/index.js:62:19)
    at new ConnectApp (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/node_modules/gulp-connect/index.js:38:10)
    at Object.module.exports.server (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/node_modules/gulp-connect/index.js:185:12)
    at Gulp.<anonymous> (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/gulpfile.js:43:13)
    at module.exports (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/Vijay/Workspace/react-router-flux-starter-kit-master/node_modules/gulp/node_modules/orchestrator/index.js:273:3)

**Comment by przeor** [comment]
hello @vbabaria what is your OS? It looks like you have already open the ports 8080 on which the app has to run so it can't listen on 8080 so you see the above error.

**Comment by przeor** [comment]
btw. @vbabaria where are you from? If you need more support please contact me on email kamil@przeorski.pl or skype przeor1989 :-) I am open to figure it out for you and help in other potential obstacles

**Comment by vbabaria** [comment]
Oops... my bad 

thanks a lot for the quick response, really appreciate it

**Comment by przeor** [comment]
contact me at @vbabaria, I am just curious what are you about to build :-) ;-) I can mentor you if you would like etc.

**Comment by przeor** [comment]
@vbabaria kamil@przeorski.pl
